sudo: false
language: cpp
compiler: 
    - g++
env:
    global:
        - OMP_NUM_THREADS=4

before_script: ls
script: 
    - make -C benchmark all
    - make -C csr_bench all
    - make travis-verify

